services:

  webui:
    build:
      context: .
      dockerfile: webui/Dockerfile
    container_name: cnap-webui
    ports:
      - "8080:8080"
    volumes:
      - ./config:/config
    environment:
      - CONFIG_FILE=/config/config.yaml

  checker-ybroslavskyi:
    build: .
    container_name: ybroslavskyi
    environment:
      - CONFIG_FILE=/config/config.yaml
      - PROFILE_NAME=ybroslavskyi
    volumes:
      - ./config:/config:ro
      - ./logs:/logs
    restart: no
    depends_on:
      - webui

  checker-stymtsiv:
    build: .
    container_name: stymtsiv
    environment:
      - CONFIG_FILE=/config/config.yaml
      - PROFILE_NAME=stymtsiv
    volumes:
      - ./config:/config:ro
      - ./logs:/logs
    restart: no
    depends_on:
      - webui
